import os
from google.oauth2 import service_account
from googleapiclient.discovery import build
from googleapiclient.errors import HttpError
from google.oauth2.credentials import Credentials
from google_auth_oauthlib.flow import InstalledAppFlow
from google.auth.transport.requests import Request
import datetime

class SlideGenerator:
    """
    Automates the creation of Google Slides presentations.
    """
    SCOPES = ['https://www.googleapis.com/auth/presentations', 'https://www.googleapis.com/auth/drive']
    INSTALL_ACCOUNT_FILE = 'local_service_account.json'
    SERVICE_ACCOUNT_FILE = 'service_account.json'

    def __init__(self):
        # Verify if the credentials exist

        creds = None
        # The file token.json stores the user's access and refresh tokens, and is
        # created automatically when the authorization flow completes for the first
        # time.
        try:
            # Load existing credentials if available
            if os.path.exists("token.json"):
                creds = Credentials.from_authorized_user_file("token.json", self.SCOPES)

            # If there are no (valid) credentials available, let the user log in.
            if not creds or not creds.valid:
                if creds and creds.expired and creds.refresh_token:
                    creds.refresh(Request())
                else:
                    flow = InstalledAppFlow.from_client_secrets_file(
                        self.INSTALL_ACCOUNT_FILE, self.SCOPES
                    )
                    creds = flow.run_local_server(port=0)
                # Save the credentials for the next run
                with open("token.json", "w") as token:
                    token.write(creds.to_json())

            # Use service account credentials for server-to-server interactions
            self.slides_service = build('slides', 'v1', credentials=creds)
            self.drive_service = build('drive', 'v3', credentials=creds)
            print("✅ [Init] Services built successfully.") # [Debug]

        except Exception as e:
            print(f"❌ [Init] Failed to build services: {e}")
            raise e

    def create_presentation(self, title):
        try:
            """Creates a new presentation and returns its ID and URL."""
            body = {'title': title}
            presentation = self.slides_service.presentations().create(body=body).execute()
            presentation_id = presentation.get('presentationId')
            print(f"Created presentation with ID: {presentation_id}")

            # Obtain the first cover slide.
            first_slide = presentation.get('slides')[0]

            # Find the placeholder IDs for "Title" and "Subtitle".
            title_object_id = None
            subtitle_object_id = None

            # Iterate through all elements on the first page and find the title box.
            for element in first_slide.get('pageElements', []):
                shape = element.get('shape')
                if not shape: continue

                placeholder = shape.get('placeholder')
                if not placeholder: continue

                type_ = placeholder.get('type')
                if type_ in ['CENTERED_TITLE', 'TITLE']:
                    title_object_id = element.get('objectId')
                elif type_ == 'SUBTITLE':
                    subtitle_object_id = element.get('objectId')

            # Prepare requests to fill in the title and subtitle.
            requests = []

            # Fill in the title
            if title_object_id:
                requests.append({
                    'insertText': {
                        'objectId': title_object_id,
                        'text': title
                    }
                })

            # Fill in the subtitle with current timestamp
            if subtitle_object_id:
                current_time = datetime.datetime.now().strftime("%Y-%m-%d %H:%M")
                requests.append({
                    'insertText': {
                        'objectId': subtitle_object_id,
                        'text': f"Generated by AI Agent at {current_time}"
                    }
                })

            # Execute the requests to update the presentation
            if requests:
                self.slides_service.presentations().batchUpdate(
                    presentationId=presentation_id,
                    body={'requests': requests}
                ).execute()


            # Set permissions to allow anyone to read the data for demo purposes ONLY
            # TODO: For production environments have to use email invitations instead
            self._share_file(presentation_id)

            return presentation_id, f"https://docs.google.com/presentation/d/{presentation_id}"

        except HttpError as err:
            print(f"❌ [Step 1] Google API Error: {err}")
            if err.resp.get('content'):
                print(f"   Details: {err.resp.content}")
            raise err

    def _share_file(self, file_id):
        """Shares the file so you can open it without logging into the service account."""
        try:
            batch = self.drive_service.permissions().create(
                fileId=file_id,
                body={'type': 'anyone', 'role': 'writer'},
                fields='id',
            ).execute()
            print("✅ [Step 1.5] Share success.")
        except HttpError as err:
            print(f"⚠️ [Step 1.5] Share Warning: {err}")

    def add_summary_slide(self, presentation_id, slide_title, summary_text):
        """Adds a slide with a title and a bulleted list of text."""

        try:
            # 1. Create a new slide
            requests = [
                {
                    'createSlide': {
                        'objectId': 'summary_slide_01',
                        'slideLayoutReference': {'predefinedLayout': 'TITLE_AND_BODY'}
                    }
                }
            ]

            # 2. Write title and content
            body = {'requests': requests}
            response = self.slides_service.presentations().batchUpdate(
                presentationId=presentation_id, body=body).execute()

            slide_id = response['replies'][0]['createSlide']['objectId']

            # 3. Get the placeholder of this page (to know where to fill in the text).
            slide = self.slides_service.presentations().pages().get(
                presentationId=presentation_id, pageObjectId=slide_id).execute()

            title_id = slide['pageElements'][0]['objectId']
            body_id = slide['pageElements'][1]['objectId']

            # 4. Request to insert text
            text_requests = [
                {
                    'insertText': {
                        'objectId': title_id,
                        'text': slide_title
                    }
                },
                {
                    'insertText': {
                        'objectId': body_id,
                        'text': summary_text
                    }
                }
            ]

            # 5. Batch update to insert text
            self.slides_service.presentations().batchUpdate(
                presentationId=presentation_id,
                body={'requests': text_requests}
            ).execute()

            print("✅ [Step 2] Slide added successfully.")

        except HttpError as err:
            print(f"❌ [Step 2] Failed to add slide: {err}")
            raise err
        except KeyError as e:
            print(f"❌ [Step 2] Failed to parse slide structure (Index Error?): {e}")
            raise e

# Test locally
if __name__ == "__main__":
    try:
        gen = SlideGenerator()
        pid, url = gen.create_presentation("Giga Factory Daily Report")
        gen.add_summary_slide(pid, "Executive Summary", "1. Yield rate is stable.\n2. BMS Issue detected in v2.1.0.")
        print(f"Success! Open here: {url}")
    except Exception as e:
        print(f"Error: {e}")